version: '3.8'

networks:
  dio_net:
    driver: bridge

services:
  dio_web:
    image: dio_web:local
    depends_on:
      dio_db:
        condition: service_healthy
      dio_chroma:
        condition: service_healthy
      dio_mcp:
        condition: service_started
    #build: #Deprecato a causa dell'immagine locale creata "dio_web:local"
    #  context: ${DIO_DATA}  # o hardcoded: /srv/cargo/volumes/maria/dio
    container_name: dio_web
    working_dir: /app
    command: python wsgi.py
    restart: unless-stopped
    ports:
      - "${DIO_PORT_WEB:-5555}:5555"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=wsgi.py
      - PIP_CACHE_DIR=${PYTHON_CACHE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_PROVIDER=${MODEL_PROVIDER:-ollama}
      - DIO_DB_HOST=${DIO_DB_HOST:-dio_db}
      - DIO_DB_PORT=${DIO_DB_PORT:-3306}
      - DIO_DB_USER=${DIO_DB_USER:-dio}
      - DIO_DB_PASS=${DIO_DB_PASS}
      - DIO_DB_NAME=${DIO_DB_NAME:-dio}
    volumes:
      - ${DIO_DATA}/app:/app
      - ${DIO_DATA}/scripts:/scripts
      - ${DIO_DATA}/logs:/logs
      - ${DIO_DATA}/memory:/memory
      - ${PYTHON_CACHE}:/${PYTHON_CACHE}
    networks:
      - dio_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

  dio_db:
    image: mariadb:11
    container_name: dio_db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${DIO_DB_ROOT_PASS}
      - MARIADB_DATABASE=${DIO_DB_NAME}
      - MARIADB_USER=${DIO_DB_USER}
      - MARIADB_PASSWORD=${DIO_DB_PASS}
    ports:
      - "${DIO_PORT_DB:-3306}:3306"
    volumes:
      - ${DIO_DATA}/db:/var/lib/mysql
    networks:
      - dio_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DIO_DB_ROOT_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
      
  dio_chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: dio_chroma
    restart: unless-stopped
    ports:
      - "${DIO_PORT_CHROMA:-8000}:8000"
    volumes:
      - ${DIO_DATA}/db/chroma:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_DB_IMPL=duckdb
    networks:
      - dio_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 512M
  dio_mcp:
    build:
      context: /srv/maria/mcp-agent
    container_name: dio_mcp
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /srv/maria/mcp-agent:/app
    command: python3 main.py
    networks:
      - dio_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M