services:
  database:
    image: mariadb:latest
    container_name: wiki-zero-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - /home/pio/.local/share/mio/srv/src/cargo/portainer/volumes/mediawiki_0/db:/var/lib/mysql
    networks:
      - wiki-net

  mediawiki:
    image: mediawiki:latest
    container_name: wiki-zero
    restart: always
    ports:
      - "1010:80"
    environment:
      DB_SERVER: database
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /home/pio/.local/share/mio/srv/src/cargo/portainer/volumes/mediawiki_0:/var/www/html
    depends_on:
      - database
    networks:
      - wiki-net

networks:
  wiki-net:
