services:
  database:
    image: mariadb:latest
    container_name: ${NAME_CONTAINER_DB}
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ${PATH_DATA}/db:/var/lib/mysql
    networks:
      - default_net

  mediawiki:
    image: mediawiki:latest
    container_name: ${NAME_CONTAINER}
    restart: always
    ports:
      - "${PORTA}:80"
    environment:
      DB_SERVER: database
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${PATH_DATA}/images:/var/www/html/images
      - ${PATH_DATA}/LocalSettings.php:/var/www/html/LocalSettings.php
      - ${PATH_DATA}/skins:/var/www/html/skins
      - ${PATH_DATA}/extensions:/var/www/html/extensions
      - ${PATH_DATA}/html:/var/www/html
    depends_on:
      - database
    networks:
      - default_net

networks:
  default_net:
    name: ${NET}
