services:
  wiki:
    image: mediawiki:1.39
    container_name: mediawiki
    restart: unless-stopped
    ports:
      - "${MW_PORT}:80"
    environment:
      MEDIAWIKI_DB_TYPE: mysql
      MEDIAWIKI_DB_HOST: db
      MEDIAWIKI_DB_NAME: ${MW_DB_NAME}
      MEDIAWIKI_DB_USER: ${MW_DB_USER}
      MEDIAWIKI_DB_PASSWORD: ${MW_DB_PASS}
    volumes:
      - ${MW_HTML_PATH}:/var/www/html
    networks:
      - wikinet
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: mediawiki_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MW_DB_NAME}
      MYSQL_USER: ${MW_DB_USER}
      MYSQL_PASSWORD: ${MW_DB_PASS}
      MYSQL_ROOT_PASSWORD: ${MW_DB_ROOT}
    volumes:
      - ${MW_DB_PATH}:/var/lib/mysql
    networks:
      - wikinet

networks:
  wikinet:
    driver: bridge
