services:
  database:
    image: mariadb:latest
    container_name: ${NAME_CONTAINER_DB:-wiki-zero-db}
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ${PATH_DATA}/db:/var/lib/mysql
    networks:
      - ${NET:-wiki-net}

  mediawiki:
    image: mediawiki:latest
    container_name: ${NAME_CONTAINER:-wiki-zero}
    restart: always
    ports:
      - "${PORTA:-1010}:80"
    environment:
      DB_SERVER: database
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${PATH_DATA}:/var/www/html
    depends_on:
      - database
    networks:
      - ${NET:-wiki-net}

networks:
  default_net:
    name: ${NET:-wiki-net}
