services:
  mariadb:
    image: mariadb:11
    container_name: db_00
    restart: unless-stopped
    env_file:
      - ../env/db_00.env
    volumes:
      - ~/SRCargo/portainer/volumes/db/00:/var/lib/mysql
    networks:
      - net_db_00

networks:
  internal_net:
    name: net_db_00
    driver: bridge
