services:
  wordpress:
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - "${WP_PORT:-8080}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASS}
    volumes:
      - ${WP_HTML_PATH}:/var/www/html
    networks:
      - wpnet

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASS}
      MYSQL_ROOT_PASSWORD: ${WP_DB_ROOT}
    volumes:
      - ${WP_DB_PATH}:/var/lib/mysql
    networks:
      - wpnet

networks:
  wpnet:
    driver: bridge
